### ISSUE TITLE
Interface Naming Convention

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp1-graph-marchand-regnard#1]
Bonjour,

Est ce qu'on peut renommer les interfaces comme par exemple IGraph en Graph ? 
D'après stack overlflow, en Java cette convention n'est pas la meilleure.
https://stackoverflow.com/a/2814831/5976559

**Comment by Slashgear** [comment]
Yes

Le mer. 28 févr. 2018 10:56, Mathieu Regnard <notifications@github.com> a
écrit :
