### ISSUE TITLE
Question 1 generification

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp1-graph-marchand-regnard#2]
Bonjour, 

Dans la question 1, doit on écrire dans le rapport les changements que nous avons effectué qui nous rien à voir avec les méthodes à implémenter ? Par exemple dans 43dc69f8752be1977df807a4f70f920e4ebaf882 on utilise la généricité de Java pour simplifier les classes qui implémentent Label pour éviter d'avoir à utiliser Object, doit-on le noter dans le rapport ?

**Comment by Slashgear** [comment]
Vous n'êtes pas obligé mais si vous avez le temps et la motivation. Allez
y, je regarderai ça avec attention :)


Le jeu. 1 mars 2018 18:39, Mathieu Regnard <notifications@github.com> a
écrit :
