### ISSUE TITLE
Code review needed

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp1-graph-marchand-regnard#3]
Bonjour, nous avons push les modifications sur la master, est-ce possible d'avoir une review de code ? 
(Nous n'avons pas fini le rapport)

**Comment by AwaitingIrindul** [comment]
On avait pas test désolé

**Comment by Slashgear** [comment]
- [ ] Ici le type pourrait être `Graph` pourquoi ? Serait-ce mieux ?
https://github.com/PolytechLyon/isi3-tp1-graph-marchand-regnard/blob/139f21377f17b8e2d6cbe72e4b1dd4a0c20ec9dd/src/main/java/graph/SimpleUndirectedGraph.java#L8

- ℹ️ Sympa votre NodeCollection mais vous réinventez un peu la roue. Vous auriez pu trouver un type abstrait commun à Queue et Stack 😉 

- [ ] un petit UML de classe dans le rapport pour me montrer les UML des patterns (cela pourrait vous être demandé au partiel)

**Comment by AwaitingIrindul** [comment]
>  Ici le type pourrait être `Graph` pourquoi ? Serait-ce mieux ?

Oui on pourrait utiliser le type `Graph` car les deux implémentent indirectement l'interface `Graph`, seulement certaines fonctions utilisées sont disponible que dans l'interface `DirectedGraph` et cela nous oblige à caster l'objet pour appeler ces fonctions. 
Par contre, on pourrait utiliser l'interface `DirectedGraph`. 

> Sympa votre NodeCollection mais vous réinventez un peu la roue. Vous auriez pu trouver un type abstrait commun à Queue et Stack 😉

Les modifications on été faites :) voir e367aac9684f34a7acd303acff682fb1dc786670

**Comment by Slashgear** [comment]
Nice
