### ISSUE TITLE
Hashcode

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp1-graph-marchand-regnard#4]
Comme nous avons override la méthode `equals()` d'`Object` dans `Node`, il faut override également `hashCode()` car deux objects qui sont égaux d'après `equals()` doivent avoir le même hashcode. 
De plus cela peut également nous permettre d'améléiorer le hashage dans les hashmap, hashset ect.. 

Pour l'instant, l'intuition que nous avons est d'utiliser le hashCode du `uniqueID` avec `Integer.hashCode(uniqueID)`. En effet comme on test l'égalité de deux `Node` en testant l'égalité de cet `uniqueID`, cela nous semble logique d'utiliser le hashcode de cette valeur. Est-ce une bonne méthode ? Si non, existe il une méthode générale pour générer des hashcode ou doit-on le faire au cas par cas ?

**Comment by Slashgear** [comment]
C'est une bonne méthode.

Et oui surcharger hashcode est une bonne pratique :-)
